# add the following to _config.yml file
title: Khaled Elzend
logo: Khaled-w-Elzend-2001/assists/images/headshot_circle.png
#description: text below image

show_downloads: true
theme: jekyll-theme-minimal
